services:
  mongo:
    image: mongo:7.0.34-jammy
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: RootP@ss4_Db
    ports:
      - "27017:27017"
    volumes:
      - /docker/volume/mongo/data:/data/db
